// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudyOrganizer.Data;

#nullable disable

namespace StudyOrganizer.Data.Migrations
{
    [DbContext(typeof(StudyContext))]
    partial class StudyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StudyOrganizer.Core.Entities.Discipline", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ModuleId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId");

                    b.ToTable("Disciplines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ModuleId = 1,
                            Name = "Língua Portuguesa"
                        },
                        new
                        {
                            Id = 2,
                            ModuleId = 1,
                            Name = "Raciocínio Lógico"
                        },
                        new
                        {
                            Id = 3,
                            ModuleId = 1,
                            Name = "Informática"
                        },
                        new
                        {
                            Id = 4,
                            ModuleId = 1,
                            Name = "Legislação"
                        },
                        new
                        {
                            Id = 5,
                            ModuleId = 2,
                            Name = "Engenharia de Software"
                        },
                        new
                        {
                            Id = 6,
                            ModuleId = 2,
                            Name = "Banco de Dados"
                        },
                        new
                        {
                            Id = 7,
                            ModuleId = 2,
                            Name = "Redes de Computadores"
                        });
                });

            modelBuilder.Entity("StudyOrganizer.Core.Entities.Module", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Modules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Conhecimentos Gerais"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Conhecimentos Específicos"
                        });
                });

            modelBuilder.Entity("StudyOrganizer.Core.Entities.StudySession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<DateTime>("SessionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SubtopicId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubtopicId");

                    b.ToTable("StudySessions");
                });

            modelBuilder.Entity("StudyOrganizer.Core.Entities.Subtopic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("DisciplineId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MasteryLevel")
                        .HasColumnType("int");

                    b.Property<string>("MaterialUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DisciplineId");

                    b.ToTable("Subtopics");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Interpretação de textos",
                            DisciplineId = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = 2,
                            Description = "Ortografia oficial",
                            DisciplineId = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = 3,
                            Description = "Acentuação gráfica",
                            DisciplineId = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = 4,
                            Description = "Proposições, conectivos e tabelas-verdade",
                            DisciplineId = 2,
                            Status = 0
                        },
                        new
                        {
                            Id = 5,
                            Description = "Problemas de lógica e contagem",
                            DisciplineId = 2,
                            Status = 0
                        },
                        new
                        {
                            Id = 6,
                            Description = "Conceitos de sistemas operacionais",
                            DisciplineId = 3,
                            Status = 0
                        },
                        new
                        {
                            Id = 7,
                            Description = "Segurança da informação",
                            DisciplineId = 3,
                            Status = 0
                        },
                        new
                        {
                            Id = 8,
                            Description = "Constituição Federal - Artigos 37 a 41",
                            DisciplineId = 4,
                            Status = 0
                        },
                        new
                        {
                            Id = 9,
                            Description = "Lei de Acesso à Informação (Lei 12.527/2011)",
                            DisciplineId = 4,
                            Status = 0
                        },
                        new
                        {
                            Id = 10,
                            Description = "Ciclo de vida de software",
                            DisciplineId = 5,
                            Status = 0
                        },
                        new
                        {
                            Id = 11,
                            Description = "UML - Casos de uso, diagramas de classes e sequência",
                            DisciplineId = 5,
                            Status = 0
                        },
                        new
                        {
                            Id = 12,
                            Description = "Modelo relacional e normalização",
                            DisciplineId = 6,
                            Status = 0
                        },
                        new
                        {
                            Id = 13,
                            Description = "SQL - comandos DDL, DML, DCL",
                            DisciplineId = 6,
                            Status = 0
                        },
                        new
                        {
                            Id = 14,
                            Description = "Modelo OSI e TCP/IP",
                            DisciplineId = 7,
                            Status = 0
                        },
                        new
                        {
                            Id = 15,
                            Description = "Endereçamento IPv4 e IPv6",
                            DisciplineId = 7,
                            Status = 0
                        });
                });

            modelBuilder.Entity("StudyOrganizer.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("StudyOrganizer.Core.Entities.Discipline", b =>
                {
                    b.HasOne("StudyOrganizer.Core.Entities.Module", "Module")
                        .WithMany("Disciplines")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");
                });

            modelBuilder.Entity("StudyOrganizer.Core.Entities.StudySession", b =>
                {
                    b.HasOne("StudyOrganizer.Core.Entities.Subtopic", "Subtopic")
                        .WithMany("StudySessions")
                        .HasForeignKey("SubtopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subtopic");
                });

            modelBuilder.Entity("StudyOrganizer.Core.Entities.Subtopic", b =>
                {
                    b.HasOne("StudyOrganizer.Core.Entities.Discipline", "Discipline")
                        .WithMany("Subtopics")
                        .HasForeignKey("DisciplineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Discipline");
                });

            modelBuilder.Entity("StudyOrganizer.Core.Entities.Discipline", b =>
                {
                    b.Navigation("Subtopics");
                });

            modelBuilder.Entity("StudyOrganizer.Core.Entities.Module", b =>
                {
                    b.Navigation("Disciplines");
                });

            modelBuilder.Entity("StudyOrganizer.Core.Entities.Subtopic", b =>
                {
                    b.Navigation("StudySessions");
                });
#pragma warning restore 612, 618
        }
    }
}
